# -*- coding: utf-8 -*-
"""All site copy + facts in one place. Only owner-confirmed facts go in BIZ.
Never add reviews, ratings, hours or awards here unless the owner supplies them."""

SITE = 'https://veteransdrywall.net'

BIZ = dict(
    name='Veteran Drywall', legal='Veteran Drywall LLC',
    phone='(941) 527-5924', phone_e164='+19415275924',
    alt='(941) 929-3545', alt_e164='+19419293545',
    email='info@veteransdrywall.net', license='SCC131152687',
    street='5390 Halkett Ter',
    facebook='https://www.facebook.com/profile.php?id=61557745545101',
    description='USMC veteran-owned drywall contractor in North Port, Florida. Drywall repair, texture matching, water and storm damage repair, ceiling repair, popcorn ceiling removal, new drywall, stucco, painting and trim across Sarasota and Charlotte counties.',
)

HG_REPAIR = 'https://homeguide.com/costs/drywall-repair-cost'
HG_POPCORN = 'https://homeguide.com/costs/popcorn-ceiling-removal-cost'
EPA_ASBESTOS = 'https://www.epa.gov/asbestos/protect-your-family-exposures-asbestos'
SRC_NOTE = f'National average ranges from <a href="{HG_REPAIR}" target="_blank" rel="noopener">HomeGuide</a> (updated Oct 2025). They are <strong>not quotes</strong> — Southwest Florida prices, access, texture and scope all change the number. Your written estimate from us is free.'

def cost_table(rows, caption=SRC_NOTE):
    body = ''.join(f'<tr><td>{a}</td><td><b>{b}</b></td><td>{c}</td></tr>' for a, b, c in rows)
    return f'<div class="table-wrap"><table class="cost"><thead><tr><th>Job</th><th>Typical U.S. range</th><th>What drives it</th></tr></thead><tbody>{body}</tbody><caption>{caption}</caption></table></div>'

IMG_SCAFFOLD = ('/assets/images/webp/drywall-window-scaffold-finishing-project.webp', '/assets/images/jpg-fallbacks/drywall-window-scaffold-finishing-project.jpg', 'Veteran Drywall finisher on a scaffold sanding new drywall around an arched window', 894, 1058)
IMG_PAINT = ('/assets/images/webp/interior-painting-drywall-finishing.webp', '/assets/images/jpg-fallbacks/interior-painting-drywall-finishing.jpg', 'Veteran Drywall crew member rolling paint over a freshly finished wall', 574, 416)
IMG_FRAME = ('/assets/images/webp/interior-remodel-framing-prep.webp', '/assets/images/jpg-fallbacks/interior-remodel-framing-prep.jpg', 'Interior remodel with exposed framing and insulation ready for new drywall', 574, 416)
IMG_CREW = ('/assets/images/webp/veteran-drywall-crew-hero.webp', '/assets/images/jpg-fallbacks/veteran-drywall-crew-hero.jpg', 'Steven, Mike and Rick of Veteran Drywall standing outdoors in North Port, Florida', 1901, 1053)

SERVICES = [
 dict(slug='drywall-repair', name='Drywall Repair', short='drywall repair', icon='hole', emoji='🔨',
      form_value='Drywall Repair / Texture Matching', form_label='Holes, cracks & patches',
      blurb='Holes, cracks, dents & nail pops',
      service_type='Drywall repair',
      title='Drywall Repair North Port FL | Holes, Cracks & Patches',
      desc='Drywall repair in North Port, Port Charlotte, Venice & Sarasota. Holes, cracks, nail pops and dents patched and texture-matched. Veteran-owned. Free estimates.',
      eyebrow='Drywall repair · No job too small',
      h1='Drywall repair that <span class="hl">disappears.</span>',
      sub='Doorknob holes, cracks, nail pops, corner bead dents and re-pipe patches — cut clean, taped, finished and texture-matched so you can’t find the repair once it’s painted.',
      img=IMG_SCAFFOLD,
      answer='Veteran Drywall LLC repairs drywall holes, cracks, nail pops and dents across North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda. Small holes are patched; larger damage is cut back and replaced. Every repair is taped, finished in multiple coats, texture-matched and left paint-ready. Estimates are free — call (941) 527-5924.',
      fixes=[('Doorknob & impact holes', 'Patched and blended — including the ones behind doors nobody wants to talk about.'),
             ('Cracks', 'Hairline and settlement cracks at corners, doors and windows, re-taped so they stay closed.'),
             ('Nail & screw pops', 'Reset, refastened and spotted so the bumps don’t return.'),
             ('Dented corner bead', 'Replaced and re-finished to a crisp, straight line.'),
             ('Re-pipe & electrical cuts', 'Access holes from plumbers and electricians closed and made invisible.'),
             ('Tape & seam failure', 'Bubbled or peeling tape cut out and re-finished.')],
      steps=[('Protect', 'We cover floors and furniture and set up dust control before anything gets cut.'),
             ('Cut back to sound drywall', 'Damaged gypsum is removed so the repair ties into solid material, backed with blocking where needed.'),
             ('Patch, tape & coat', 'New drywall or a patch goes in, then tape and joint compound in multiple coats with drying time between them.'),
             ('Sand & match texture', 'Feathered wide so there’s no hump, then the surrounding texture — knockdown, orange peel, skip trowel or smooth — is reproduced.'),
             ('Prime & walk through', 'Primed and ready for paint (or painted, if you want us to), then a final walkthrough with you.')],
      cost_html='<h2>How much does drywall repair cost?</h2><p>We price every job after seeing it — photos usually get you a number fast. For context, here are national averages:</p>' + cost_table([
             ('Small hole (under 4")', '$300 – $500', 'Most pros have a minimum trip/job charge; texture and paint matching add time.'),
             ('Large hole', '$500 – $800+', 'Size, whether framing or blocking is needed, texture type.'),
             ('Crack repair', '$350 – $1,000+', 'Length, cause (settling vs. seam failure), ceiling vs. wall.'),
             ('Larger sections (per sq ft)', '$3 – $8 / sq ft', 'Full-sheet replacement, height, access, finish level.')]) + '<p><a class="link-arrow" href="/drywall-repair-cost/">Full drywall repair cost guide</a></p>',
      local_html='<h2>Why repairs in Southwest Florida need extra care</h2><p>Humidity slows joint compound drying, so rushing coats is a common reason patches crack or show through paint here. We give each coat the time it needs — which is why most repairs take two or three short visits rather than one long one. Most homes in North Port, Port Charlotte and Venice have knockdown or orange peel texture, so a patch that isn’t re-textured sticks out immediately.</p>',
      faqs=[('How long does a drywall repair take?', 'Most small-to-medium repairs take one to three visits because joint compound needs drying time between coats — especially in Florida humidity. You’ll get a realistic timeline with your estimate.'),
            ('Do you take small jobs?', 'Yes. Doorknob holes, a single crack or a couple of nail pops are a core part of what we do every week.'),
            ('Will I be able to see the patch?', 'That’s the whole point of texture matching. We feather the repair wide, reproduce your texture and prime it so it disappears under paint.'),
            ('Do you paint after the repair?', 'We can. Repairs are always left primed and paint-ready; if you want us to paint the wall or room, we’ll include it in your estimate.'),
            ('What should I send for a quote?', 'Two or three photos (one close, one from across the room), rough size and your city. That’s usually enough for an accurate estimate.')]),

 dict(slug='texture-matching', name='Texture Matching', short='texture matching', icon='dots', emoji='🎯',
      form_value='Texture Matching', form_label='Match my texture',
      blurb='Knockdown, orange peel, skip trowel, smooth',
      service_type='Drywall texture matching',
      title='Drywall Texture Matching | Knockdown & Orange Peel, FL',
      desc='Knockdown, orange peel, skip trowel, popcorn and Level 5 smooth texture matching in North Port, Port Charlotte, Venice & Sarasota. Repairs that blend in.',
      eyebrow='Our specialty',
      h1='Texture matching so good it <span class="hl">vanishes.</span>',
      sub='Patching drywall is one thing. Making the repair invisible is the craft. We reproduce the exact texture already on your wall or ceiling — knockdown, orange peel, skip trowel, popcorn or smooth.',
      img=IMG_PAINT,
      answer='Texture matching means reproducing the existing wall or ceiling pattern over a drywall repair so it blends in. Veteran Drywall LLC matches knockdown, orange peel, skip trowel, popcorn and smooth (Level 5) finishes — plus exterior stucco — across North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda.',
      fixes=[('Knockdown', 'The most common Florida texture — splattered compound flattened with a knockdown knife into soft, flat-topped islands.'),
             ('Orange peel', 'A fine sprayed texture with a subtle dimpled look, common in newer construction.'),
             ('Skip trowel', 'Hand-troweled, irregular ridges — popular in higher-end and Mediterranean-style homes.'),
             ('Popcorn / acoustic', 'Matched for small patches, or removed entirely. See popcorn ceiling removal.'),
             ('Smooth / Level 5', 'A full skim coat for a flat, modern finish with no texture at all.'),
             ('Stucco', 'Exterior patches matched to the surrounding profile and sand finish.')],
      steps=[('Identify the texture', 'We look at pattern size, spacing, height and how the paint sits on it — two “knockdowns” can look very different.'),
             ('Test before we commit', 'Pressure, nozzle, compound thickness and knockdown timing are dialed in on a test board first.'),
             ('Feather the edges', 'The new texture is blended out past the patch so there is no hard line between old and new.'),
             ('Prime & paint', 'Primer evens out absorption; paint that matches in sheen finishes the illusion.')],
      extra_html='<div class="note"><strong>Honest note:</strong> texture that’s been painted many times, or paint that has faded in sunlight, can make any repair visible until the whole wall is repainted. We’ll tell you up front if repainting the full wall (corner to corner) is the only way to make it truly disappear.</div>',
      cost_html='<h2>What does texture matching cost?</h2><p>Texture is usually part of the repair price. National figures for texturing alone:</p>' + cost_table([
             ('Texturing (per sq ft)', '$0.80 – $2.00+ / sq ft', 'Matching an existing pattern costs more than texturing a blank wall.'),
             ('Taping, mudding & finishing', '$1.50 – $3.50 / sq ft', 'Finish level (Level 4 vs. Level 5), ceiling height, access.')]),
      local_html='<h2>Common textures in Southwest Florida homes</h2><p>Across North Port, Port Charlotte and Punta Gorda, knockdown on walls and ceilings is the most common finish we see, followed by orange peel in newer builds. Older Port Charlotte and Venice homes often still have popcorn ceilings. Coastal condos in Sarasota and Venice are more likely to have smooth or skip-trowel finishes.</p>',
      faqs=[('Can you match my existing texture exactly?', 'In most cases, yes. We test the pattern on a board first. If fading or many layers of paint mean a perfect blend isn’t possible, we’ll tell you before we start and recommend repainting the full wall.'),
            ('What is the difference between knockdown and orange peel?', 'Orange peel is a fine sprayed dimple texture. Knockdown is heavier splatter that’s flattened with a knife into smooth-topped islands. Knockdown is the most common texture in Southwest Florida homes.'),
            ('Can you make a textured wall smooth?', 'Yes. A Level 5 skim coat covers existing texture for a flat, modern finish.'),
            ('Do you match ceiling texture too?', 'Yes — ceiling repairs are blended the same way, including popcorn patches when you’re keeping the popcorn.')]),

 dict(slug='water-damage-drywall-repair', name='Water & Storm Damage', short='water damage repair', icon='drop', emoji='💧',
      form_value='Water-Damaged Drywall Repair', form_label='Water / storm damage',
      blurb='Leaks, flood cuts, hurricane damage',
      service_type='Water damaged drywall repair',
      title='Water Damaged Drywall Repair | North Port & Port Charlotte',
      desc='Water-damaged drywall and ceiling repair after leaks, AC overflows, hurricanes and flooding in North Port, Port Charlotte, Punta Gorda, Venice & Sarasota.',
      eyebrow='Storm & leak repair',
      h1='Water-damaged drywall, <span class="hl">rebuilt right.</span>',
      sub='Plumbing leaks, AC pan overflows, roof leaks, hurricane flood cuts — once the source is fixed and the area is dry, we replace the damaged drywall and finish it back to like-new.',
      img=IMG_FRAME,
      answer='Yes — water-damaged drywall can be repaired. Once the leak is fixed and the wall cavity is dry, the wet or stained drywall is cut out, replaced, taped, finished, texture-matched and primed. Veteran Drywall LLC does this across North Port, Port Charlotte, Punta Gorda, Venice, Sarasota and Englewood.',
      fixes=[('Ceiling stains & sagging', 'AC pan overflows and roof leaks usually show up on the ceiling first.'),
             ('Soft or swollen walls', 'Drywall that’s soaked through loses strength and has to be replaced, not painted over.'),
             ('Flood cuts', 'Walls cut at 2–4 ft after flooding, rehung and finished seamlessly to the original drywall.'),
             ('Plumbing & re-pipe damage', 'Leak damage plus the access holes the plumber left behind.'),
             ('Hurricane & storm damage', 'Interior drywall and ceilings damaged by wind-driven rain or roof failure.'),
             ('Stain bleed-through', 'Water stains sealed with the right primer so they don’t reappear through new paint.')],
      steps=[('Stop the source', 'The leak must be fixed first — by a plumber, roofer or AC tech as needed.'),
             ('Confirm it’s dry', 'Wet framing and insulation behind drywall must be dry before closing the wall up.'),
             ('Remove damaged drywall', 'Stained, soft or swollen drywall (and wet insulation) is cut out back to sound material.'),
             ('Rehang, tape & finish', 'New drywall — moisture-resistant where appropriate — is hung and finished in multiple coats.'),
             ('Match texture, seal & prime', 'Texture is matched and stain-blocking primer applied so nothing bleeds through the paint.')],
      extra_html='<div class="note"><strong>Safety first:</strong> if a leak is still active, or you suspect mold, electrical damage or structural problems, have that assessed by the right licensed professional first. Once the area is safe and dry, we handle the drywall and finish. We don’t perform mold remediation.</div><h2>After a hurricane or flood</h2><p>Charlotte and Sarasota counties have been hit hard by recent storms — Hurricane Ian in 2022, and Helene and Milton in 2024. After a storm, photograph all damage before anything is removed, call your insurance carrier, and let the property dry out. When you’re ready to put walls back together, we’ll provide a detailed written estimate you can share with your adjuster.</p>',
      cost_html='<h2>How much does water damage drywall repair cost?</h2><p>Water damage is priced after we see it — the size of the affected area, ceiling vs. wall and whether insulation needs replacing all change the number. Send photos for a fast estimate. For reference, national averages for the drywall portion: ceiling repairs <b>$350 – $1,500+</b> and larger sections <b>$3 – $8 per sq ft</b> (<a href="' + HG_REPAIR + '" target="_blank" rel="noopener">HomeGuide</a>, not a quote).</p>',
      local_html='',
      faqs=[('Can water-damaged drywall be dried out instead of replaced?', 'Sometimes, if it got briefly wet from clean water and stayed firm. Drywall that is soft, swollen, crumbling, sagging or stained through usually has to be cut out and replaced.'),
            ('How long after a leak can drywall be repaired?', 'As soon as the leak is fixed and the wall or ceiling cavity has fully dried. Closing up a wet cavity traps moisture and invites mold.'),
            ('Do you work with insurance claims?', 'We provide detailed written estimates and photos you can share with your insurance adjuster. Coverage decisions are between you and your carrier.'),
            ('Do you remove mold?', 'No. If you suspect mold, have it assessed and remediated by a qualified professional first. We handle the drywall once the area is safe and dry.'),
            ('Will the water stain come back through the paint?', 'Not if it’s sealed properly. We use a stain-blocking primer before paint so the stain doesn’t bleed through.')]),

 dict(slug='ceiling-repair', name='Ceiling Repair', short='ceiling repair', icon='ceiling', emoji='🏠',
      form_value='Ceiling Repair', form_label='Ceiling repair',
      blurb='Cracks, sags, stains & nail pops',
      service_type='Drywall ceiling repair',
      title='Ceiling Repair North Port & Port Charlotte | Cracks, Stains',
      desc='Drywall ceiling repair for cracks, sagging, water stains and nail pops in North Port, Port Charlotte, Venice & Sarasota. Texture matched. Free estimates.',
      eyebrow='Ceiling repair',
      h1='Ceiling cracks, sags &amp; stains — <span class="hl">gone.</span>',
      sub='Ceilings are harder than walls: gravity, lighting that shows every flaw, and textures that are tough to blend. It’s work we do every week.',
      img=IMG_SCAFFOLD,
      answer='Veteran Drywall LLC repairs drywall ceilings across North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda — cracks, sagging panels, water stains, nail pops and truss-uplift cracks — then matches the ceiling texture and primes so the repair disappears.',
      fixes=[('Ceiling cracks', 'Along seams, at corners and at the wall-ceiling joint.'),
             ('Sagging drywall', 'Refastened or replaced — sagging is often a sign of past moisture.'),
             ('Water stains', 'Sealed or replaced depending on whether the drywall is still sound.'),
             ('Nail pops', 'Common on ceilings; reset and spotted.'),
             ('Light & fan relocations', 'Old holes closed, new openings cut and finished.'),
             ('Texture blending', 'Knockdown, orange peel, popcorn or smooth.')],
      steps=[('Find the cause', 'A crack or stain is a symptom — we look for the leak, loose fastening or movement behind it.'),
             ('Protect the room', 'Ceiling work is messy; floors and furniture are covered first.'),
             ('Repair or replace', 'Cracks re-taped, sagging sections refastened or replaced.'),
             ('Match & prime', 'Texture reproduced and blended, then primed.')],
      cost_html='<h2>Ceiling repair cost</h2>' + cost_table([
             ('Ceiling repair', '$350 – $1,500+', 'Size, height, texture, whether a leak caused it.'),
             ('Crack repair', '$350 – $1,000+', 'Length and cause.')]),
      local_html='<h2>Why Florida ceilings crack</h2><p>Most Florida ceiling problems we see trace back to AC condensate pan overflows, roof leaks after storms, or seasonal movement of roof trusses (often called truss uplift), which shows up as cracks where the ceiling meets interior walls. We fix the finish and point you to the right trade if there’s a leak or structural issue to address first.</p>',
      faqs=[('Why is my ceiling cracking?', 'Common causes are settling, seasonal roof-truss movement, a failed tape joint, or moisture from an AC or roof leak. We’ll look at the pattern and tell you which it likely is.'),
            ('Is a sagging ceiling dangerous?', 'A sagging ceiling can indicate water damage or failed fastening. If it’s actively bulging or wet, keep people out from under it and call right away.'),
            ('Can you repair just part of a popcorn ceiling?', 'Yes, we can patch popcorn. Many homeowners use the opportunity to remove it entirely — see popcorn ceiling removal.')]),

 dict(slug='popcorn-ceiling-removal', name='Popcorn Ceiling Removal', short='popcorn ceiling removal', icon='popcorn', emoji='✨',
      form_value='Popcorn Ceiling Removal', form_label='Remove popcorn ceiling',
      blurb='Scrape, repair & refinish',
      service_type='Popcorn ceiling removal',
      title='Popcorn Ceiling Removal North Port & Port Charlotte FL',
      desc='Popcorn ceiling removal and refinishing — smooth, knockdown or orange peel — in North Port, Port Charlotte, Venice & Sarasota, with asbestos-testing guidance.',
      eyebrow='Popcorn ceiling removal',
      h1='Popcorn ceilings, <span class="hl">scraped &amp; modernized.</span>',
      sub='Out with the bumpy acoustic texture. We scrape, repair, and refinish smooth, knockdown or orange peel — with the room protected start to finish.',
      img=IMG_PAINT,
      answer='Popcorn ceiling removal means scraping off the acoustic texture, repairing the drywall underneath, and refinishing it smooth or with a new texture. In homes built before the mid-1980s, the texture should be tested for asbestos by an accredited lab before it is disturbed. Veteran Drywall LLC removes and refinishes popcorn ceilings across North Port, Port Charlotte, Venice, Sarasota and Punta Gorda.',
      fixes=[('Full-room removal', 'Scraped, cleaned and refinished.'),
             ('Whole-house removal', 'Room-by-room so you can keep living in the house.'),
             ('Smooth finish', 'Skim-coated for a clean, modern Level 5 ceiling.'),
             ('New texture', 'Light knockdown or orange peel if you prefer some texture.'),
             ('Painted popcorn', 'Harder to scrape — we assess and plan accordingly.'),
             ('Patch only', 'Keeping the popcorn? We can patch and match it.')],
      steps=[('Test if needed', 'For older homes, get the texture tested for asbestos before anything is scraped.'),
             ('Seal the room', 'Floors, walls and fixtures are covered in plastic; HVAC vents sealed.'),
             ('Scrape & repair', 'Texture removed, seams and dings repaired.'),
             ('Skim & finish', 'Smooth skim coat or new texture applied and sanded.'),
             ('Prime, paint & clean up', 'Primed (and painted if included), then plastic comes down and debris is removed.')],
      extra_html=f'<div class="note"><strong>Asbestos warning:</strong> popcorn ceilings installed before the mid-1980s may contain asbestos. Don’t scrape, sand or drill into it until a sample has been tested by an accredited lab. If it tests positive, removal must be handled by a licensed asbestos abatement contractor. See the <a href="{EPA_ASBESTOS}" target="_blank" rel="noopener">EPA’s guidance on asbestos in the home</a>.</div>',
      cost_html='<h2>Popcorn ceiling removal cost</h2>' + cost_table([
             ('Removal only', '$1 – $2 / sq ft', 'Painted popcorn and high ceilings take longer.'),
             ('Removal + texture + paint', '$2 – $6 / sq ft', 'Smooth (Level 5) costs more than a new knockdown.'),
             ('Typical whole job', '$2,000 – $9,000', 'Square footage of ceiling, number of rooms, furniture.'),
             ('Asbestos testing', '$250 – $850', 'Lab testing before removal in older homes.')], caption=f'National averages from <a href="{HG_POPCORN}" target="_blank" rel="noopener">HomeGuide</a>. Not a quote — your written estimate is free.'),
      local_html='<h2>Popcorn in Southwest Florida homes</h2><p>Many older homes in Port Charlotte, Punta Gorda and Venice were built during decades when popcorn ceilings were standard, so we see a lot of them — especially in homes being updated for sale or rental. Newer North Port and Wellen Park-area homes rarely have it.</p>',
      faqs=[('Does my popcorn ceiling have asbestos?', 'You can’t tell by looking. Homes built before the mid-1980s should have a sample tested by an accredited lab before removal. Newer homes are much less likely to contain it, but testing is inexpensive peace of mind.'),
            ('How long does popcorn ceiling removal take?', 'A typical room takes a couple of days including drying time between coats; a whole house is scheduled room by room.'),
            ('Can you remove painted popcorn?', 'Yes, but paint makes the texture harder to soften and scrape, so it takes longer. We’ll factor that into your estimate.'),
            ('Smooth or textured after removal?', 'Your choice. Smooth looks the most modern but shows every imperfection under strong light; a light knockdown is more forgiving.')]),

 dict(slug='new-construction-drywall', name='New Drywall & Remodels', short='drywall installation', icon='house', emoji='🏗️',
      form_value='New Construction Drywall', form_label='New drywall / remodel',
      blurb='Hang, tape & finish — additions to full builds',
      service_type='Drywall installation and finishing',
      title='Drywall Installation North Port FL | Remodels & New Builds',
      desc='Drywall hanging, taping and finishing for new construction, additions, remodels and garage conversions in North Port, Port Charlotte, Venice & Sarasota.',
      eyebrow='New construction & remodels',
      h1='From bare studs to <span class="hl">paint-ready.</span>',
      sub='Hanging, taping and finishing for additions, remodels, garage conversions and new builds. Straight walls, crisp corners, and a crew that shows up when the schedule says.',
      img=IMG_FRAME,
      answer='Veteran Drywall LLC hangs, tapes and finishes drywall for new construction, additions, remodels and garage conversions across North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda — Level 4 or Level 5 finishes, texture of your choice, coordinated with your general contractor’s schedule.',
      fixes=[('Additions & conversions', 'Garages, lanais and bonus rooms turned into living space.'),
             ('Kitchen & bath remodels', 'Including moisture-resistant board where it belongs.'),
             ('New builds', 'Hang and finish crews for builders and GCs.'),
             ('Framing', 'Wall changes and blocking where the project needs it.'),
             ('Level 5 finishes', 'Skim-coated for smooth walls under raking light.'),
             ('Texture of your choice', 'Knockdown, orange peel, skip trowel or smooth.')],
      steps=[('Walk the job', 'Scope, finish level and schedule set up front — in writing.'),
             ('Hang', 'Board laid out to minimize seams and butt joints.'),
             ('Tape & finish', 'Corners, seams and fasteners finished in multiple coats.'),
             ('Texture or skim', 'Your chosen finish applied and sanded.'),
             ('Punch & walkthrough', 'We walk it with you or your GC before calling it done.')],
      cost_html='<h2>Drywall finishing costs</h2>' + cost_table([
             ('Taping, mudding & finishing', '$1.50 – $3.50 / sq ft', 'Finish level, ceiling height, corners and openings.'),
             ('Texturing', '$0.80 – $2.00+ / sq ft', 'Pattern and whether it must match existing areas.')]),
      local_html='',
      faqs=[('Do you work with general contractors?', 'Yes. We coordinate with your GC’s schedule so drywall doesn’t hold up the job.'),
            ('What’s a Level 5 finish?', 'A thin skim coat of compound over the entire surface after taping, for the smoothest possible wall. It’s recommended for smooth walls and ceilings under strong or raking light.'),
            ('Do you handle small remodels?', 'Yes — a single bathroom or a closet conversion is fine.')]),

 dict(slug='stucco-repair', name='Stucco Repair', short='stucco repair', icon='trowel', emoji='🧱',
      form_value='Stucco Repair', form_label='Stucco repair',
      blurb='Cracks & patches matched outside',
      service_type='Stucco repair',
      title='Stucco Repair North Port & Port Charlotte FL',
      desc='Exterior stucco crack repair and patching matched to your existing texture in North Port, Port Charlotte, Venice, Sarasota, Englewood & Punta Gorda.',
      eyebrow='Stucco repair',
      h1='Stucco repairs that <span class="hl">match outside, too.</span>',
      sub='Cracks, holes from removed fixtures, and damaged patches repaired and matched to your existing stucco texture — then ready for paint.',
      img=None,
      answer='Veteran Drywall LLC repairs exterior stucco — cracks, holes from removed fixtures and damaged sections — and matches the patch to the surrounding texture so it blends in once painted. We serve North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda.',
      fixes=[('Stucco cracks', 'Opened, filled and re-textured.'),
             ('Fixture & pipe holes', 'Old lights, hose bibs and cable penetrations closed.'),
             ('Impact damage', 'Chipped corners and damaged sections rebuilt.'),
             ('Texture match', 'Sand finish and patterns reproduced.'),
             ('Paint-ready', 'Cured and ready for your painter — or painted by us.'),
             ('Small interior-exterior combos', 'One crew for the drywall inside and stucco outside.')],
      steps=[('Assess', 'We check whether a crack is cosmetic or a sign of moisture getting in.'),
             ('Prep', 'Loose material removed and the area prepared.'),
             ('Patch & texture', 'Built back up and textured to match.'),
             ('Cure & paint', 'Allowed to cure before paint for a lasting finish.')],
      cost_html='<h2>Stucco repair cost</h2><p>Stucco work is priced after we see it — size, height and texture all matter. Send a photo from close up and one from farther back for a fast estimate.</p>',
      local_html='<h2>Florida sun is tough on stucco</h2><p>UV fades painted stucco, which is why a perfectly matched patch can still look different until the wall is repainted. We’ll tell you honestly whether spot-painting will blend or whether painting the full wall section is the better move.</p>',
      faqs=[('Are stucco cracks serious?', 'Most hairline cracks are cosmetic, but wider or growing cracks can let water in. We’ll tell you what we see; structural concerns should be checked by the right professional.'),
            ('Will a stucco patch match?', 'We match the texture closely. Paint color and sun-fading usually decide whether the patch disappears, so we may recommend repainting the full wall section.')]),

 dict(slug='painting-trim', name='Painting, Carpentry & Trim', short='painting & trim', icon='roller', emoji='🎨',
      form_value='Painting & Trim', form_label='Painting & trim',
      blurb='Interior/exterior paint, baseboards, crown',
      service_type='Painting and finish carpentry',
      title='Painting, Trim & Carpentry North Port FL | Veteran Drywall',
      desc='Interior and exterior painting, baseboards, casing, crown molding and finish carpentry in North Port, Port Charlotte, Venice & Sarasota. Veteran-owned.',
      eyebrow='The finishing touches',
      h1='Paint &amp; trim that make it <span class="hl">look done.</span>',
      sub='Interior and exterior paint, baseboards, door casing, crown molding and custom carpentry — so your drywall project finishes with one crew and no hand-offs.',
      img=IMG_PAINT,
      answer='Along with drywall, Veteran Drywall LLC handles interior and exterior painting, baseboards, casing, crown molding, framing and finish carpentry across North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda — so repairs and remodels are finished by one accountable crew.',
      fixes=[('Interior painting', 'Walls and ceilings with sharp cut lines.'),
             ('Exterior painting', 'Stucco and trim, prepped for Florida sun.'),
             ('Baseboards & casing', 'Installed, caulked and painted.'),
             ('Crown molding', 'Tight miters and clean reveals.'),
             ('Framing', 'Wall changes, soffits and blocking.'),
             ('Finish carpentry', 'Custom details that finish a remodel.')],
      steps=[('Prep', 'Patching, caulking and sanding before any paint.'),
             ('Protect', 'Floors, furniture and fixtures covered.'),
             ('Prime & paint', 'The right primer, then finish coats.'),
             ('Trim out', 'Tight joints, filled nail holes, clean caulk lines.')],
      cost_html='<h2>Painting cost</h2><p>National averages for interior painting run about <b>$2 – $8+ per sq ft</b> (<a href="' + HG_REPAIR + '" target="_blank" rel="noopener">HomeGuide</a>). When painting follows our drywall work, it’s usually quoted together.</p>',
      local_html='',
      faqs=[('Do you only paint after drywall work?', 'Painting is usually the finishing step of our drywall and stucco jobs, but ask about standalone painting and trim projects too.'),
            ('Do you install baseboards after flood cuts?', 'Yes — after flood cuts we can rehang drywall, finish it, and reinstall or replace baseboards and paint.')]),

 dict(slug='property-managers', name='Property Manager Punch Lists', short='punch-list repairs', icon='clipboard', emoji='🔑',
      form_value='Property Manager / Realtor / Landlord Service', form_label='Rental / listing punch list',
      blurb='Turnovers, move-outs & listing prep',
      service_type='Rental turnover and listing prep drywall repairs',
      title='Drywall Punch Lists for Property Managers & Realtors',
      desc='Turnover, move-out and listing-prep drywall, texture, paint and punch-list repairs for property managers, landlords and realtors in North Port & Port Charlotte.',
      eyebrow='Built for turnover speed',
      h1='Punch lists done. <span class="hl">Units rent-ready.</span>',
      sub='Tenant damage, move-out repairs, listing prep and inspection punch lists — handled by one reliable crew that communicates, documents and shows up.',
      img=IMG_CREW,
      answer='Veteran Drywall LLC works with property managers, landlords, investors and realtors across North Port, Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda on tenant-damage repairs, move-out punch lists, listing prep and inspection items — drywall, texture, paint and trim, with photo documentation available.',
      fixes=[('Tenant damage', 'Holes, dents and scuffs patched and painted.'),
             ('Move-out repairs', 'Full punch lists between tenants.'),
             ('Listing prep', 'Walls and ceilings photo-ready before the listing goes live.'),
             ('Inspection items', 'Drywall and finish items from buyer inspections.'),
             ('Ceiling stains', 'Sealed or replaced after leaks.'),
             ('Documentation', 'Before/after photos for owners and HOAs.')],
      steps=[('Send the list', 'Addresses, walkthrough photos or the inspection report.'),
             ('Get a straight quote', 'Itemized so owners know what they’re paying for.'),
             ('We coordinate access', 'Lockbox or meet-up — whatever fits your process.'),
             ('Photo sign-off', 'Before/after photos when it’s done.')],
      cost_html='', local_html='',
      faqs=[('Can you work in occupied rentals?', 'Yes, with notice to tenants coordinated through you. We protect belongings and clean up daily.'),
            ('Do you provide documentation for HOAs or owners?', 'Yes — license information, written estimates and before/after photos are available on request.'),
            ('Can you handle multiple properties?', 'Yes. Send the list and we’ll quote and schedule them together.')]),
]

CITIES = [
 dict(slug='north-port-fl', name='North Port', county='Sarasota County', wiki='https://en.wikipedia.org/wiki/North_Port,_Florida',
      title='Drywall Repair North Port FL | Local Veteran-Owned Crew',
      desc='North Port’s veteran-owned drywall contractor: repairs, texture matching, water & storm damage, ceilings, popcorn removal. Based in 34286. Call (941) 527-5924.',
      h1='Drywall repair in <span class="hl">North Port, FL</span>',
      sub='This is home base. Veteran Drywall is based in North Port (34286), so local repairs, estimates and follow-ups are close by.',
      img=IMG_CREW,
      answer='Veteran Drywall LLC is a USMC veteran-owned drywall contractor based in North Port, FL 34286. We repair drywall holes, cracks, ceilings and water damage, match knockdown and orange peel textures, remove popcorn ceilings, and hang and finish new drywall throughout North Port. Free estimates: (941) 527-5924.',
      nearby=['Wellen Park', 'Heron Creek', 'Bobcat Trail', 'Warm Mineral Springs', 'Myakka River area neighborhoods', 'Toledo Blade and Sumter Blvd corridors'],
      body_html='<h2>Your neighbors in North Port</h2><p>North Port is the largest city in Sarasota County and, according to the city, passed 100,000 residents in 2026 (<a href="https://www.mysuncoast.com/2026/09/17/north-port-population-tops-100000/" target="_blank" rel="noopener">ABC7 Sarasota</a>). It keeps growing — new construction in Wellen Park and the West Villages sits alongside established neighborhoods built over the past few decades. That mix means we see everything: builder-grade orange peel that needs matching, knockdown ceilings with AC-leak stains, and remodels that take older homes down to the studs.</p><h2>Common jobs we handle in North Port</h2><ul><li><strong>Storm and flood repairs</strong> — parts of North Port flooded during Hurricane Ian in 2022, and flood-cut drywall is still a big part of local rebuild work.</li><li><strong>AC and plumbing leak ceilings</strong> — stained, sagging ceiling drywall replaced and texture-matched.</li><li><strong>Texture matching</strong> on knockdown and orange peel for patches that disappear.</li><li><strong>Remodels and additions</strong> — hang, tape and finish to paint-ready.</li></ul>',
      faqs=[('Are you actually based in North Port?', 'Yes. Veteran Drywall LLC is based in North Port, FL 34286 — it’s our home base.'),
            ('Do you work in Wellen Park?', 'Yes, we serve Wellen Park and the surrounding West Villages area.'),
            ('How fast can I get an estimate in North Port?', 'Send photos through the estimate form or call (941) 527-5924. Most estimates come back within one business day.')]),

 dict(slug='port-charlotte-fl', name='Port Charlotte', county='Charlotte County', wiki='https://en.wikipedia.org/wiki/Port_Charlotte,_Florida',
      title='Drywall Repair Port Charlotte FL | Veteran Drywall',
      desc='Drywall repair in Port Charlotte, FL: holes, cracks, water-damaged ceilings, popcorn removal and texture matching. USMC veteran-owned, FL SCC131152687.',
      h1='Drywall repair in <span class="hl">Port Charlotte, FL</span>',
      sub='Just down US-41 from our North Port base, Port Charlotte is one of our busiest service areas — older homes, lots of popcorn ceilings, and plenty of storm history.',
      img=IMG_SCAFFOLD,
      answer='Veteran Drywall LLC repairs drywall in Port Charlotte, FL — holes, cracks, water- and storm-damaged ceilings, popcorn ceiling removal and knockdown or orange peel texture matching. We’re a USMC veteran-owned contractor (FL license SCC131152687) based next door in North Port. Free estimates: (941) 527-5924.',
      nearby=['Murdock', 'Harbour Heights', 'Charlotte Harbor', 'Gulf Cove', 'El Jobean', 'Deep Creek'],
      body_html='<h2>Port Charlotte homes, Port Charlotte problems</h2><p>Port Charlotte grew out of a planned community developed from the 1950s onward, so much of the housing stock is older than in neighboring North Port. In practice that means more popcorn ceilings, more layers of paint over old texture, and more patch-over-patch repairs that need to be done properly this time.</p><p>Charlotte County has also taken repeated hurricane hits — Hurricane Charley in 2004 and Hurricane Ian in 2022 among them — and water-damaged ceilings and flood-cut walls remain some of our most common Port Charlotte calls.</p><h2>Most-requested in Port Charlotte</h2><ul><li><a href="/popcorn-ceiling-removal/">Popcorn ceiling removal</a> (with asbestos testing for older homes)</li><li><a href="/water-damage-drywall-repair/">Water &amp; storm damage repair</a></li><li><a href="/texture-matching/">Texture matching</a> over old patches</li><li><a href="/property-managers/">Rental turnover</a> punch lists</li></ul>',
      faqs=[('Do you serve all of Port Charlotte?', 'Yes, including Murdock, Harbour Heights and the surrounding Charlotte County communities.'),
            ('Is my Port Charlotte popcorn ceiling safe to remove?', 'If the home was built before the mid-1980s, have the texture tested for asbestos by an accredited lab first. If it’s clear, we can remove and refinish it.'),
            ('Can you repair hurricane-damaged drywall?', 'Yes — once the roof or leak is fixed and the area is dry, we replace damaged drywall and match the finish.')]),

 dict(slug='venice-fl', name='Venice', county='Sarasota County', wiki='https://en.wikipedia.org/wiki/Venice,_Florida',
      title='Drywall Repair Venice FL | Texture Matching & Ceilings',
      desc='Drywall repair and texture matching in Venice, FL — ceilings, water damage, popcorn removal and remodels. USMC veteran-owned, from nearby North Port.',
      h1='Drywall repair in <span class="hl">Venice, FL</span>',
      sub='From Venice Island to South Venice and Venice Gardens — careful, clean repairs for homes and condos, finished to match.',
      img=IMG_PAINT,
      answer='Veteran Drywall LLC provides drywall repair, texture matching, ceiling and water-damage repair, popcorn ceiling removal and remodel finishing in Venice, FL. We’re a USMC veteran-owned contractor based in nearby North Port. Free estimates: (941) 527-5924.',
      nearby=['Venice Island', 'South Venice', 'Venice Gardens', 'Nokomis', 'Osprey', 'Laurel'],
      body_html='<h2>Working in Venice homes and condos</h2><p>Venice has a wide mix of housing — historic-district homes on the island, mid-century neighborhoods, newer developments inland, and a lot of condos. Condo work comes with HOA rules on work hours, access and documentation, and we’re used to working within them and providing license information when a board asks.</p><p>Many Venice interiors have smooth or skip-trowel finishes that are less forgiving than knockdown, so feathering and priming matter even more.</p><h2>What we do most in Venice</h2><ul><li><a href="/ceiling-repair/">Ceiling repair</a> after AC and roof leaks</li><li><a href="/texture-matching/">Skip trowel and smooth texture matching</a></li><li><a href="/popcorn-ceiling-removal/">Popcorn removal</a> in older homes</li><li><a href="/new-construction-drywall/">Remodel finishing</a></li></ul>',
      faqs=[('Do you work in Venice condos?', 'Yes. We follow HOA rules on hours and access and can provide license documentation for your association.'),
            ('Can you match skip trowel texture?', 'Yes — skip trowel is hand-applied, and we test the pattern before applying it to your wall.')]),

 dict(slug='sarasota-fl', name='Sarasota', county='Sarasota County', wiki='https://en.wikipedia.org/wiki/Sarasota,_Florida',
      title='Drywall Repair Sarasota FL | Veteran-Owned Contractor',
      desc='Veteran-owned drywall repair in Sarasota, FL: storm and water damage, ceilings, Level 5 smooth finishes, texture matching, popcorn removal. Free estimates.',
      h1='Drywall repair in <span class="hl">Sarasota, FL</span>',
      sub='Storm repairs, ceiling fixes and flawless Level 5 finishes for Sarasota homes and condos — from a veteran-owned crew based just south in North Port.',
      img=IMG_FRAME,
      answer='Veteran Drywall LLC serves Sarasota, FL with drywall repair, water and storm damage repair, ceiling repair, Level 5 smooth finishes, texture matching and popcorn ceiling removal. We’re a USMC veteran-owned, Florida-licensed (SCC131152687) contractor based in North Port. Free estimates: (941) 527-5924.',
      nearby=['South Sarasota', 'Gulf Gate', 'Palmer Ranch', 'Osprey', 'Southgate', 'Siesta Key (mainland side)'],
      body_html='<h2>Sarasota: storm recovery and high-end finishes</h2><p>Hurricane Milton made landfall near Siesta Key in October 2024, weeks after Hurricane Helene’s surge, and many Sarasota homes are still working through interior repairs. We replace water-damaged drywall once homes are dry and provide detailed written estimates homeowners can share with insurance adjusters.</p><p>Sarasota also has a lot of modern and mid-century architecture with smooth walls and big windows — exactly the lighting that exposes a bad patch. That’s where a true <a href="/new-construction-drywall/">Level 5 finish</a> earns its keep.</p>',
      faqs=[('Do you travel to Sarasota from North Port?', 'Yes, Sarasota is part of our regular service area.'),
            ('Do you do Level 5 smooth finishes?', 'Yes. We skim-coat for Level 5 finishes on smooth walls and ceilings, where raking light shows every flaw.')]),

 dict(slug='englewood-fl', name='Englewood', county='Sarasota & Charlotte Counties', wiki='https://en.wikipedia.org/wiki/Englewood,_Florida',
      title='Drywall Repair Englewood FL | Storm & Ceiling Repair',
      desc='Drywall repair in Englewood, FL on both the Sarasota and Charlotte County sides: storm and flood damage, ceilings, texture matching. Veteran-owned. Free estimates.',
      h1='Drywall repair in <span class="hl">Englewood, FL</span>',
      sub='Coastal homes take a beating. We rebuild storm- and leak-damaged drywall on both sides of the county line.',
      img=IMG_SCAFFOLD,
      answer='Veteran Drywall LLC repairs drywall in Englewood, FL — on both the Sarasota County and Charlotte County sides — including storm and flood damage, ceiling repairs, texture matching and popcorn ceiling removal. USMC veteran-owned and based in nearby North Port. Free estimates: (941) 527-5924.',
      nearby=['Rotonda West', 'Cape Haze', 'Placida', 'Manasota Key', 'Grove City', 'Lemon Bay area'],
      body_html='<h2>Englewood straddles two counties — we cover both</h2><p>Englewood sits across the Sarasota–Charlotte county line, so neighbors a few streets apart deal with different county offices. For drywall work, it doesn’t matter which side you’re on — we cover both.</p><p>Englewood and the Lemon Bay area took heavy storm surge and wind-driven rain in recent hurricane seasons. Common jobs here are flood cuts, water-stained ceilings and replacing drywall behind removed baseboards and cabinets.</p>',
      faqs=[('Do you serve Rotonda West?', 'Yes, Rotonda West and the Cape Haze area are part of our Englewood-area coverage.'),
            ('Can you rehang drywall after a flood cut?', 'Yes — once the walls are dry, we hang new drywall, blend it into the original, and can reinstall baseboards and paint.')]),

 dict(slug='punta-gorda-fl', name='Punta Gorda', county='Charlotte County', wiki='https://en.wikipedia.org/wiki/Punta_Gorda,_Florida',
      title='Drywall Repair Punta Gorda FL | Veteran Drywall',
      desc='Drywall repair in Punta Gorda, FL: water and storm damage, ceilings, texture matching, popcorn removal and remodels. USMC veteran-owned. Free estimates.',
      h1='Drywall repair in <span class="hl">Punta Gorda, FL</span>',
      sub='From Punta Gorda Isles canal homes to Burnt Store and Deep Creek — clean, precise drywall work for Charlotte County’s county seat.',
      img=IMG_PAINT,
      answer='Veteran Drywall LLC repairs drywall in Punta Gorda, FL, including water and storm damage, ceiling repair, texture matching, popcorn ceiling removal and remodel finishing. We’re a USMC veteran-owned, Florida-licensed (SCC131152687) contractor. Free estimates: (941) 527-5924.',
      nearby=['Punta Gorda Isles', 'Burnt Store Isles', 'Deep Creek', 'Burnt Store Lakes', 'Solana', 'Downtown Punta Gorda'],
      body_html='<h2>Built back stronger</h2><p>Punta Gorda is the Charlotte County seat, and it knows storms: Hurricane Charley made landfall near here in 2004, and Hurricane Ian brought damage again in 2022. A lot of local drywall work is still storm-related — ceilings, flood cuts and water-stained walls — alongside remodels in canal-front homes.</p><p>Waterfront and canal homes often mean humidity and AC condensation issues, which is why we seal stains properly and use moisture-resistant board where it belongs.</p>',
      faqs=[('Do you work in Punta Gorda Isles?', 'Yes, including Punta Gorda Isles and Burnt Store Isles canal homes.'),
            ('Do you use moisture-resistant drywall?', 'Where it’s appropriate — bathrooms, laundry areas and some rebuilds — we use moisture-resistant board.')]),
]

# Picker panel data used on the homepage (also serialized into JS)
PICKER = {
 'hole': dict(tag='Drywall hole repair', title='Hole in the wall', short='drywall repair', url='/drywall-repair/', service='Drywall Repair / Texture Matching',
              desc='Doorknob hits, furniture dings, accidents. Small holes get a patch; bigger ones are cut back and replaced with new drywall.',
              steps=['Cut back to solid drywall', 'Patch, tape & 2–3 coats', 'Texture-matched & primed'], time='2–3 short visits', cost='$300 – $800+ typical U.S.'),
 'crack': dict(tag='Crack & nail pop repair', title='Cracks & nail pops', short='drywall repair', url='/drywall-repair/', service='Drywall Repair / Texture Matching',
              desc='Settling cracks at corners and doors, popped screws, failed tape seams — re-taped so they stay closed.',
              steps=['Open & re-tape the crack', 'Reset popped fasteners', 'Feather, texture & prime'], time='1–3 visits', cost='$350 – $1,000+ typical U.S.'),
 'ceiling': dict(tag='Ceiling repair', title='Ceiling stain or sag', short='ceiling repair', url='/ceiling-repair/', service='Ceiling Repair',
              desc='Usually an AC pan overflow or roof leak. We find the cause, then seal or replace the ceiling drywall and match the texture.',
              steps=['Confirm the leak is fixed', 'Seal or replace damaged drywall', 'Match ceiling texture'], time='1–3 visits', cost='$350 – $1,500+ typical U.S.'),
 'water': dict(tag='Water & storm damage', title='Water or storm damage', short='water damage repair', url='/water-damage-drywall-repair/', service='Water-Damaged Drywall Repair',
              desc='Soft, swollen or stained drywall from leaks, flooding or hurricanes. Once it’s dry, we cut it out, rehang and finish.',
              steps=['Source fixed & area dry', 'Remove wet drywall & insulation', 'Rehang, finish, stain-block prime'], time='Depends on size', cost='Priced after photos / visit'),
 'texture': dict(tag='Texture matching', title='Patch sticks out', short='texture matching', url='/texture-matching/', service='Texture Matching',
              desc='An old repair that’s smooth on a knockdown wall (or vice versa). We reproduce your exact texture so it blends in.',
              steps=['Identify the texture', 'Test on a board first', 'Blend wide & prime'], time='1–2 visits', cost='$0.80 – $2+/sq ft typical U.S.'),
 'popcorn': dict(tag='Popcorn ceiling removal', title='Popcorn ceilings', short='popcorn removal', url='/popcorn-ceiling-removal/', service='Popcorn Ceiling Removal',
              desc='Scraped and refinished smooth or with a light knockdown. Older homes: get the texture tested for asbestos first.',
              steps=['Asbestos test (older homes)', 'Seal the room & scrape', 'Skim, texture & prime'], time='~2 days per room', cost='$2 – $6/sq ft finished, typical U.S.'),
 'remodel': dict(tag='New drywall & remodels', title='Remodel or addition', short='drywall installation', url='/new-construction-drywall/', service='New Construction Drywall',
              desc='Garage conversions, additions, kitchen and bath remodels — hung, taped and finished to paint-ready.',
              steps=['Scope & schedule in writing', 'Hang, tape & finish', 'Texture or Level 5 skim'], time='Scheduled per project', cost='$1.50 – $3.50/sq ft finishing, typical U.S.'),
 'stucco': dict(tag='Stucco repair', title='Stucco cracks outside', short='stucco repair', url='/stucco-repair/', service='Stucco Repair',
              desc='Cracks, fixture holes and damaged sections patched and matched to your existing stucco texture.',
              steps=['Assess for moisture entry', 'Patch & re-texture', 'Cure, then paint'], time='1–2 visits + cure', cost='Priced after photos / visit'),
}
PICKER_ORDER = [('hole', 'Hole in wall', 'hole'), ('crack', 'Cracks / nail pops', 'crack'), ('ceiling', 'Ceiling stain / sag', 'ceiling'), ('water', 'Water / storm damage', 'drop'),
                ('texture', 'Patch sticks out', 'dots'), ('popcorn', 'Popcorn ceiling', 'popcorn'), ('remodel', 'Remodel / addition', 'house'), ('stucco', 'Stucco outside', 'trowel')]

TEXTURES = {
 'knockdown': 'Knockdown — splattered compound flattened into soft, flat-topped islands. The most common wall and ceiling texture in Southwest Florida homes.',
 'orangepeel': 'Orange peel — a fine sprayed texture with a subtle dimpled look, common in newer construction around North Port.',
 'skiptrowel': 'Skip trowel — hand-troweled, irregular ridges. Popular in higher-end and Mediterranean-style homes; every hand is a little different, so we test first.',
 'popcorn': 'Popcorn — the bumpy acoustic ceiling texture. We can patch and match it, or remove it entirely (test older homes for asbestos first).',
 'smooth': 'Smooth / Level 5 — a full skim coat for a flat, modern wall. The least forgiving finish under raking light, so the prep has to be perfect.',
}

GENERAL_FAQS = [
 ('Do you offer free drywall estimates?', 'Yes — estimates are free. Call <a href="tel:+19415275924">(941) 527-5924</a> or use the <a href="/free-estimate/">estimate form</a> with a few photos. Most estimates come back within one business day.'),
 ('Is Veteran Drywall licensed?', 'Yes. Veteran Drywall LLC holds Florida license # SCC131152687, which you can verify on the Florida DBPR license lookup. We can provide documentation for HOAs and property managers on request.'),
 ('Who owns Veteran Drywall?', 'Steven McPherson, a U.S. Marine Corps veteran with more than a decade of service and four overseas deployments. He runs the business with his crew, Mike and Rick.'),
 ('What areas do you serve?', 'We’re based in North Port and serve Port Charlotte, Venice, Sarasota, Englewood and Punta Gorda across Sarasota and Charlotte counties. Nearby but not listed? Call and ask.'),
 ('Do you handle small drywall repairs?', 'Yes. No job is too small — doorknob holes, a single crack, nail pops and small ceiling stains are a core part of what we do.'),
 ('Can you match my existing wall or ceiling texture?', 'Yes. Texture matching is our specialty — knockdown, orange peel, skip trowel, popcorn and smooth Level 5 — so repairs blend in instead of standing out.'),
 ('Do you repair water-damaged drywall?', 'Yes. Once the source of the leak is fixed and the area is dry, we remove damaged drywall, rehang, finish, match texture and seal with stain-blocking primer.'),
 ('Do you remove popcorn ceilings?', 'Yes — we scrape and refinish smooth or with a new texture. Homes built before the mid-1980s should have the texture tested for asbestos first.'),
 ('How long does a typical drywall repair take?', 'Most small-to-medium repairs take one to three visits because joint compound needs drying time between coats. We’ll give you a realistic timeline in your estimate.'),
 ('What should I send for a quote?', 'Two or three photos (one close, one from across the room), rough size of the damage, and your city. That’s usually enough for an accurate estimate.'),
 ('Do you work with landlords, realtors and property managers?', 'Yes — tenant damage, move-out punch lists, listing prep and inspection items, with photo documentation available.'),
 ('How much does drywall repair cost?', 'It depends on size, texture and access; we price every job after seeing photos or the space. National averages run roughly $300–$500 for a small hole and $500–$800+ for large holes (HomeGuide). See our <a href="/drywall-repair-cost/">cost guide</a>.'),
]
